rspec_4_finish_yoshioka
yoshi-sho-0606/rspec_app_exam pull request #1
Opened 2021-01-28 05:05 UTC by yoshi-sho-0606

rspec編4終了

2021-01-28 05:52 UTC, yuji91 requested changes
修正のコミットは、指摘事項ごとにコミットの単位を分けてください。

2021-01-28 05:52 UTC, yuji91 commented on spec/factories/tasks.rb
> +    trait :finish_task do
今回はtaskのstatusと同名のtrait名で伝わるかと思います。
```suggestion
    trait :done do
```

2021-01-28 05:52 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = FactoryBot.create(:task, :finish_task)
こちらも省略しておきましょう
```suggestion
        task = create(:task, :finish_task)
```

2021-01-28 05:52 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content(Time.current.strftime('%-m/%d %R'))
こちらの修正ですが、失敗例のPRと同様の内容となっています。確認をお願いします。

2021-01-30 07:19 UTC, yoshi-sho-0606 reviewed
課題修正しました

2021-01-30 07:29 UTC, yuji91 requested changes
こちら細かい点を指摘しました。

2021-01-30 07:29 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = FactoryBot.create(:task, project_id: project.id, title: 'task_1')
この記載も省略できる部分は省略しましょう。
```suggestion
        task = create(:task, title: 'task_1')
```

2021-01-30 07:29 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
変数名を変えておいた方がデータがどのような内容かが伝わりやすいです。
```suggestion
        done_task = create(:task, :done)
```

2021-01-30 07:53 UTC, yoshi-sho-0606 commented on spec/system/task_spec.rb
> +        task = FactoryBot.create(:task, project_id: project.id, title: 'task_1')
5f731f42a2e9dbb9ba959a601d815d20b8f71299 不必要な記載を省略しました

2021-01-30 07:54 UTC, yoshi-sho-0606 commented on spec/system/task_spec.rb
> +        task = create(:task, :done)
abf599a048cd375b28a3cf2d01df4e4e08ed9b5c　変数名を変更しました

2021-01-30 08:28 UTC, yuji91 requested changes
残り1点、対応をお願いします。

2021-01-30 08:28 UTC, yuji91 commented on spec/system/task_spec.rb
> +        done_task = create(:task, :done)
こちら`let!`で定義して、それを呼び出す形にすると変数としてテストケース内で宣言する必要が無くなります。
```suggestion
```

2021-02-04 01:09 UTC, yoshi-sho-0606 commented on spec/system/task_spec.rb
> +        done_task = create(:task, :done)
41b212eb780d98196eb6f826813a68bd7e6e256f  let!による定義を行いました

2021-02-04 02:15 UTC, yuji91 approved these changes

2021-02-05 00:06 UTC, merged